Models/AddContainer.cs
using System.ComponentModel.DataAnnotations;

namespace AzureLearning.Models
{
    public class AddContainer
    {
        [Required]
        public string? ContainerName { get; set; }

    }
}

Models/BlobDetails.cs
namespace AzureLearning.Models
{
    public class BlobDetails
    {
        public string BlobName { get; set; }=string.Empty;
        public string Url {  get; set; }=string.Empty;
        public string BlobType { get; set; } = string.Empty;
    }
}

Models/ErrorViewModel.cs
namespace AzureLearning.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BlobController.cs
using AzureLearning.IServices;
using AzureLearning.Models;
using Microsoft.AspNetCore.Mvc;

namespace AzureLearning.Controllers
{
    public class BlobController : Controller
    {
        private readonly IBlobService _blobService;
        public BlobController(IBlobService blobService) 
        { 
            _blobService=blobService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string name)
        {
            List<string> blobNames =await  _blobService.GetAllBlobsAsync(name);
            return View(blobNames);
        }
        [HttpGet]
        public async Task<IActionResult> GetAllBlobsWithUrl(string name)
        {
            List<BlobDetails> blobDetails =await _blobService.GetBlobsWithFullUrlAsync(name);
            return View(blobDetails);
        }
        public IActionResult BlobWithTheContainerUrl()
        {
            return View();
        }
        public IActionResult ViewBlobItem(string containerName, string blobName)
        {
            BlobDetails blobDetails= _blobService.GetABlobAsync(containerName, blobName);
            return View(blobDetails);
        }
    }
}

Controllers/ContainerController.cs
using AzureLearning.IServices;
using Microsoft.AspNetCore.Mvc;

namespace AzureLearning.Controllers
{
    public class ContainerController : Controller
    {
        private readonly IContainerService _containerService;
        public ContainerController(IContainerService containerService) 
        { 
            _containerService = containerService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<string> containers =await _containerService.GetContainers();
            return View(containers);
        }
        public IActionResult AddContainer()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddContainer(string containerName)
        {
            await _containerService.AddContainer(containerName);
            return View();
        }
    }
}

Controllers/HomeController.cs
using AzureLearning.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AzureLearning.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Blob/BlobWithTheContainerUrl.cshtml
@{
    ViewData["Title"] = "BlobWithTheContainerUrl";
}

<h1>BlobWithTheContainerUrl</h1>
<video width="640" height="360" controls>
    <source src="@Context.Request.Query["bloburl"]">
    Your browser does not support the video tag.
</video>

Views/Blob/GetAllBlobsWithUrl.cshtml
@model List<BlobDetails>
@{
    ViewData["Title"] = "GetAllBlobsWithUrl";
}

<h3>Container Name is :- <span class="text-primary">@Context.Request.Query["name"]</span></h3>

@if (Model.Any())
{
    <ul class="list-unstyled">
        @foreach (BlobDetails blobname in Model)
        {
            <li><a asp-action="BlobWithTheContainerUrl" asp-route-containerName="@Context.Request.Query["name"]" asp-route-bloburl="@blobname.Url" class="text-decoration-none">@blobname.BlobName</a></li>
        }
    </ul>
}
else
{
    <div class="alert alert-warning m-3">
        <span>No Records Found</span>
    </div>
}

Views/Blob/Index.cshtml
@model List<string>
@{
    ViewBag.title = "manage-container";
}
<h3>Container Name is :- <span class="text-primary">@Context.Request.Query["name"]</span></h3>

@if (Model.Any())
{
    <ul class="list-unstyled">
        @foreach(string blobname in Model)
        {
            <li><a  asp-action="ViewBlobItem" asp-route-containerName="@Context.Request.Query["name"]" asp-route-blobName="@blobname" class="text-decoration-none">@blobname</a></li>
        }
    </ul>
}
else
{
    <div class="alert alert-warning m-3">
        <span>No Records Found</span>
    </div>
}

Views/Blob/ViewBlobItem.cshtml
@model BlobDetails
@{
    ViewData["Title"] = "ViewBlobItem";
}

<h3>Container Name is :- <span class="text-primary">@Context.Request.Query["containername"]</span> Blob Name is :- <span class="text-primary">@Context.Request.Query["blobname"]</span></h3>
<video width="640" height="360" controls>
    <source src="@Model.Url" type="@Model.BlobType">
    Your browser does not support the video tag.
</video>

Views/Container/AddContainer.cshtml
@model AddContainer
@{
    ViewBag.title = "AddContainer";
}
<p>Add container</p>
<form method="post" asp-action="AddContainer">
    <div class="mt-1">
    <input class="form-control" asp-for="ContainerName" placeholder="enter add-container name" />
    <span class="text-danger" asp-validation-for="ContainerName"></span>
    </div>
    <button class="btn btn-primary">Add Container</button>
</form>

Views/Container/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<string>
@{
    ViewData["title"] = "ContainersList";
}
<a class="btn btn-primary p-1 float-end" asp-action="AddContainer">Add Container</a>
@if (!Model.Any())
{
    <p class="alert alert-warning  w-75">No container is found</p>
}
else
{
    foreach (string containerName in Model)
    {
        <div class="d-flex m-2">
            <p class="text-primary">@containerName</p>
            <div class="m-2">
                <a class="btn btn-primary p-1" asp-action="Index" asp-controller="blob" asp-route-name="@containerName">Manage</a>
                <a class="btn btn-primary p-1" asp-action="GetAllBlobsWithUrl" asp-controller="blob" asp-route-name="@containerName">BlogWithFullUrl</a>
                <a class="btn btn-danger p-1">Delete</a>
            </div>
        </div>
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzureLearning</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AzureLearning.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzureLearning</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Container" asp-action="Index">Containers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AzureLearning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>